spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.107:9411/
  cloud:
    gateway:
      routes:
      - id: manageCurrConversionFactorms
        uri: lb://manageCurrConversionFactorms
        predicates:
        - Path=/currencyfactor/**
        
      - id: currencyConversionms
        uri: lb://manageCurrConversionFactorms
        predicates:
        - Path=/currencyconverter/**       
management:
  endpoints:
    web:
      exposure:
        include: '*'
 

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.url:http://localhost:8761/eureka} 