server:
  port: 8008
spring:
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:currconvDb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://192.168.99.107:9411}
  sleuth:
    trace-id128: true
    enabled: true
    sampler:
      probability: 1.0   
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.url:http://localhost:8761/eureka}

    
  
      