apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: apigateway
    version: v1
  name: apigateway
spec: 
  ports: 
    - 
      name: http
      port: 9081
      targetPort: 9081
  selector: 
    app: apigateway
    version: v1
  type: NodePort