apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: apigateway
    version: v1
  name: apigateway
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: apigateway
      version: v1
  template: 
    metadata: 
      labels: 
        app: apigateway
        version: v1
    spec: 
      containers: 
        - image: "rajashree/apigateway25:1"
          name: apigateway
          ports: 
          - containerPort: 9081
          env:
            - name: eureka.uri
              value: "http://eurekaserver:8761/eureka"
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "768Mi"
                cpu: "400m"                
