apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: currencyconversionms
    version: v1
  name: currencyconversionms
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: currencyconversionms
      version: v1
  template: 
    metadata: 
      labels: 
        app: currencyconversionms
        version: v1
    spec: 
      containers: 
        - image: "rajashree/currencyconversionms25:1"
          imagePullPolicy: Always
          name: currencyconversionms
          env:
            - name: eureka.uri
              value: "http://eurekaserver:8761/eureka"
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "768Mi"
                cpu: "400m"                
