apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: eurekaserver
    version: v1
  name: eurekaserver
spec: 
  ports: 
    - 
      name: http
      port: 8761
      targetPort: 8761
  selector: 
    app: eurekaserver
    version: v1
  type: NodePort