apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: eurekaserver
    version: v1
  name: eurekaserver
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: eurekaserver
      version: v1
  template: 
    metadata: 
      labels: 
        app: eurekaserver
        version: v1
    spec: 
      containers: 
        - 
          image: "rajashree/eurekaserver25:1"
          imagePullPolicy: Always
          name: eurekaserver
          ports: 
            - 
              containerPort: 8761
              name: http
              protocol: TCP

          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "768Mi"
                cpu: "400m"                 
