apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: managecurrencyConversionFactor
    version: v1
  name: managecurrencyConversionFactor
spec: 
  ports: 
    - 
      name: http
      port: 8008
      targetPort: 8008
  selector: 
    app: managecurrencyConversionFactor
    version: v1
  type: NodePort